application: kennethtrytek
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: mnflights.app.app

libraries:
- name: django
  version: "latest"

- name: pycrypto
  version: "latest"

- name: webapp2
  version: "latest"
